from typing import Any, Optional, Protocol


class CacheClient(Protocol):
    async def get(self, key: str) -> Optional[Any]: ...
    async def set(self, key: str, value: Any, ex: Optional[int] = None) -> None: ...
    async def incr(self, key: str) -> int: ...
    async def expire(self, key: str, seconds: int) -> None: ...
    async def delete(self, key: str) -> None: ...
