from typing import List, Optional, Protocol


class RolePermissionRepository(Protocol):
    """Protocol for role and permission repository operations."""

    async def create_role(self, name: str, description: Optional[str] = None) -> dict: ...

    async def create_permission(self, name: str, description: Optional[str] = None) -> dict: ...

    async def get_role_by_name(self, name: str): ...
    async def get_permission_by_name(self, name: str): ...
    async def get_permissions_by_names(self, names: List[str]) -> List[dict]: ...
    async def list_permissions(self) -> List[dict]: ...
    async def list_role_permissions(self, role_id: int) -> List[dict]: ...
    async def clear_role_permissions(self, role_id: int) -> None: ...

    async def assign_permission_to_role(self, role_id: int, permission_id: int) -> None: ...

    async def bulk_assign_permissions_to_role(
        self, role_id: int, permission_ids: List[int]
    ) -> None: ...

    async def remove_permission_from_role(self, role_id: int, permission_id: int) -> None: ...

    async def list_user_permissions(self, user_id: int) -> List[str]: ...
    async def get_role_permissions(self, role: str) -> List[str]: ...
    async def set_role_permissions(self, role: str, permissions: List[str]) -> None: ...
