from typing import List, Optional, Protocol

from ...domain.tenant import Tenant


class TenantRepository(Protocol):
    """Protocol for tenant repository operations."""

    async def create(self, tenant: Tenant) -> Tenant: ...
    async def get_by_id(self, id: int) -> Optional[Tenant]: ...
    async def get_by_slug(self, slug: str) -> Optional[Tenant]: ...
    async def list(self) -> List[Tenant]: ...
    async def list_all(self) -> List[Tenant]: ...
    async def update(self, id: int, **fields) -> Optional[Tenant]: ...
    async def delete(self, id: int) -> None: ...
