from typing import List, Optional, Protocol

from ...domain.user import User


class UserRepository(Protocol):
    """Protocol for user repository operations."""

    async def create(self, user: User) -> User: ...
    async def get_by_email(self, tenant_id: int, email: str) -> Optional[User]: ...
    async def get_by_email_global(self, email: str) -> Optional[User]: ...
    async def get_by_id(self, id: int) -> Optional[User]: ...
    async def list_by_tenant(self, tenant_id: int) -> List[User]: ...
    async def delete(self, id: int) -> None: ...
    async def update(self, id: int, **fields) -> Optional[User]: ...
    async def set_password(self, user_id: int, hashed_password: str) -> None: ...
    async def update_last_login(self, user_id: int, when) -> None: ...
    async def set_email(self, user_id: int, new_email: str) -> None: ...
