run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gofmt
    - goimports
    - revive
    - copyloopvar
    - prealloc
    - ineffassign
    - gocognit
    - gocyclo
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  revive:
    rules:
      - name: exported
        disabled: true

  gosec:
    excludes:
      - G204
      - G301
      - G302
      - G304
      - G404

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - goconst
