run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - unparam
    - unconvert
    - goconst
    - gocognit
    - prealloc
    - revive
    - exportloopref
    - nilerr

linters-settings:
  gosec:
    excludes:
      - G204 # Subprocess launched with variable
      - G301 # Poor file permissions used when creating a directory
      - G302 # Poor file permissions used with chmod
      - G304 # File path provided as taint input
      - G404 # Use of weak random number generator

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  revive:
    rules:
      - name: exported
        disabled: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - goconst
